GET http://localhost:3000/


###
# Get Patient
GET http://localhost:3000/api/v1/patients


###
# Create Patient
POST http://localhost:3000/api/v1/patients
Content-Type: application/json

{
    "nom": "lo",
    "prenom": "saliou",
    "email": "losaliou.sl33@gmail.com",
    "password": "passer",
    "passwordConfirm": "passer",
    "groupeSanguin": "AB+"
}

###
# Create User
POST http://localhost:3000/api/v1/users/signup
Content-Type: application/json

{
    "nom" : "lo",
    "prenom" : "serigne saliou",
    "email" : "saliou.lo.sl@gmail.com",
    "password" : "passer",
    "passwordConfirm": "passer",
    "groupeSanguin" : "O-",
    "__t" : "Patient"
}

###
# Login
POST http://localhost:3000/api/v1/users/login
Content-Type: application/json

{
    "email": "losaliou.sl33@gmail.com",
    "password": "passer"
}


###
# Logout
GET http://localhost:3000/api/v1/users/logout


###
# Forgot Password
POST http://localhost:3000/api/v1/users/forgotPassword
Content-Type: application/json

{
    "email" : "saliou.lo.sl@gmail.com"
}

###
# resetPasword
PATCH http://localhost:3000/api/v1/users/resetPassword/e96ec36e6fba3fd091a1961ca6d78b0743bdf892f383ec7f526073c54a34420f
Content-Type: application/json

{
    "password": "passer",
    "passwordConfirm": "passer"
}